### PR TITLE
start authRoute

### PR DESCRIPTION
**Pull request by yardthip-yd**
add authRoute

### CODE REVIEW

**Review by Supakorn2539 — APPROVED** [review]
VeryGood

**Review by papinwit-l — APPROVED** [review]
Ok เลย

**Review by chonlathanme — COMMENTED** [review]
mai ok

**Review by Supakorn2539 — CHANGES_REQUESTED** [review]
Please Change Code

**Review by Samach-C — COMMENTED** [review]
good code

**Review by Supakorn2539 — APPROVED** [review]

**Pull request merged**
